### ISSUE TITLE
if I only use kmeans || on mappreduce, which file should i use?

### ISSUE THREAD

**Issue by londist** [MarkusHarmsen/KMeansOnMapReduce#1]

**Comment by MarkusHarmsen** [comment]
Hey @londist,

could you please elaborate your question a bit more (background, etc.)?

**Comment by londist** [comment]
One of the tasks I have in class is to implement scalable k means ++ on Hadoop and compare it with k means. And I want to use your program to finish it. Is this suitable?  Many thanks for your reply

**Comment by MarkusHarmsen** [comment]
Maybe, I don't know your task. That's a thing only you could figure out.

`KMeans||` is in the folder `KMeans__` since  pipes in directory names might be tricky depending on the OS.
